apiVersion: kargo.akuity.io/v1alpha1
kind: Warehouse
metadata:
  name: wh-main
  namespace: demo
spec:
  subscriptions:
  - image:
      repoURL: ghcr.io/stefanprodan/podinfo
      semverConstraint: ^6.0.0
