apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-shard
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo-shard
  template:
    metadata:
      labels:
        app: demo-shard
    spec:
      containers:
      - name: podinfo
        image: ghcr.io/stefanprodan/podinfo
        ports:
        - containerPort: 9898
