apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-main
  namesapce: demo-main
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo-main
  template:
    metadata:
      labels:
        app: demo-main
    spec:
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80
